type User @table {
  id: UUID! @default(expr: "uuidV4()")
  email: String
}

type Movie @table {
  title: String!
  imageUrl: String!
  genre: String
}

type Review @table(key: ["movie", "user"]) {
  user: User!
  movie: Movie!
  rating: Int
  reviewText: String
  reviewDate: Date! @default(expr: "request.time")
}
